FBru.WebAdmin/Controllers/Api/CategoriesController.cs
using FBru.DTO;
using FBru.Repository.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;

namespace FBru.WebAdmin.Controllers.Api
{
    [RoutePrefix("api")]
    public class CategoriesController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [Route("categories")]
        public async Task<IEnumerable<CategoryWithIconDto>> GetCategories()
        {
            var categories = await _unitOfWork.Categories.GetCategoriesWithIcon();

            return categories;
        }
    }
}

FBru.WebAdmin/Controllers/Api/RestaurantsController.cs
using FBru.Repository.Interfaces;
using FBru.WebAdmin.Helpers;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace FBru.WebAdmin.Controllers.Api
{
    [RoutePrefix("api")]
    public class RestaurantsController : ApiController
    {
        private const int MaxPageSize = 10;

        private readonly IUnitOfWork _unitOfWork;

        public RestaurantsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Route("restaurants/{id}", Name = "RestaurantForId")]
        public async Task<IHttpActionResult> Get(int? id)
        {
            if (id == null)
                return BadRequest();

            var restaurant = await _unitOfWork.Restaurants.GetRestaurantWithDishesHaveCategoryDto(id.Value);

            if (restaurant == null)
                return NotFound();

            restaurant.ImageUrl = Constrains.ServerUrl + restaurant.ImageUrl;

            restaurant.Dishes.ForEach(d => d.ImageUrl = Constrains.ServerUrl + d.ImageUrl);

            return Ok(restaurant);
        }

        [Route("restaurants/v1/page/{page}/{pageSize}", Name = "RestaurantsList")]
        public async Task<IHttpActionResult> Get(int page = 1, int pageSize = MaxPageSize)
        {
            var restaurants = await _unitOfWork.Restaurants.GetRestaurantsWithNumberOfDishes();

            var restaurantsArray = restaurants.ToArray();

            var totalCount = restaurantsArray.Count();
            var totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

            var paginationHeader = new
            {
                currentPage = page,
                pageSize,
                totalCount,
                totalPages
            };

            HttpContext.Current.Response.Headers.Add("X-Pagination",
                JsonConvert.SerializeObject(paginationHeader));

            var skip = pageSize * (page - 1);
            var takeLimited = totalCount - skip;
            var take = pageSize;
            if (pageSize > takeLimited)
                take = takeLimited;

            var restaurantsDto = restaurantsArray.Skip(skip).Take(take).ToList();
            restaurantsDto.ForEach(r => r.ImageUrl = Constrains.ServerUrl + r.ImageUrl);

            return Ok(restaurantsArray.Skip(skip).Take(take).ToList());
        }
    }
}

FBru.WebAdmin/Controllers/ImagesController.cs
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FBru.Repository.Entities;
using FBru.Repository.Interfaces;
using FBru.WebAdmin.Helpers;

namespace FBru.WebAdmin.Controllers
{
    [AuthorizeFilter]
    public class ImagesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ImagesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Images
        public async Task<ActionResult> Index()
        {
            var images = await _unitOfWork.Images.GetImagesWithDish();

            return View(images);
        }

        public async Task<ActionResult> Create(int? id)
        {
            var dishes = await _unitOfWork.Dishes.GetDishesWithSimpleDetail();

            if (id != null)
            {
                if (dishes.Single(d => d.Id == id.Value) == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                ViewBag.DishId = new SelectList(dishes, "Id", "Name", id);
            }
            else
            {
                ViewBag.DishId = new SelectList(dishes, "Id", "Name");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Create(
            [Bind(Include = "DishId, Name, IsDisplay")] Image model)
        {
            var returnUrl = "/Images";

            var filesKey = Request.Files.AllKeys;

            if (!ModelState.IsValid || !filesKey.Any())
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                    message: @"Please enter all fields are required!"), JsonRequestBehavior.AllowGet);

            var dish = await _unitOfWork.Dishes.Get(model.DishId);

            if (dish == null)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.BadRequest, "/Images/Create"),
                    JsonRequestBehavior.AllowGet);

            var httpPostedFileBases = new HttpPostedFileBase[filesKey.Length];

            for (var i = 0; i < filesKey.Length; i++)
            {
                var imageUpload = Request.Files[filesKey[i]];
                var validateFile = Utilities.HttpPostedFileBaseFilter(imageUpload);
                if (validateFile >= 0)
                {
                    var error = Utilities.HttpPostedFileBaseErrorMessage(validateFile);
                    return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                        message: error), JsonRequestBehavior.AllowGet);
                }
                httpPostedFileBases[i] = Request.Files[filesKey[i]];
            }

            var originalDirectory = new DirectoryInfo(Server.MapPath("~/Content/Dishes"));
            var directoryPath = Path.Combine(originalDirectory.ToString(), dish.Name);

            if (!Directory.Exists(directoryPath))
                Directory.CreateDirectory(directoryPath);

            foreach (var imageUpload in httpPostedFileBases)
                try
                {
                    var fileName = Guid.NewGuid() + ".jpg";
                    imageUpload.SaveAs(Path.Combine(directoryPath, fileName));
                    var image = new Image
                    {
                        DishId = model.DishId,
                        Name = model.Name,
                        IsDisplay = model.IsDisplay,
                        Url = $"Content/Dishes/{dish.Name}/{fileName}"
                    };
                    _unitOfWork.Images.Add(image);
                }
                catch (Exception)
                {
                    foreach (var image in httpPostedFileBases)
                    {
                        var filePath = Path.Combine(directoryPath, image.FileName);
                        if (System.IO.File.Exists(filePath)) System.IO.File.Delete(filePath);
                    }
                    return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.ServerError,
                        "/Images/Create"), JsonRequestBehavior.AllowGet);
                }

            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Success,
                    message: @"These images added to this dish successfully!", returnUrl: returnUrl),
                JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int? id)
        {
            var returnUrl = "/Images";

            if (id == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl),
                    JsonRequestBehavior.AllowGet);

            var image = await _unitOfWork.Images.Get(id.Value);

            if (image == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        message: "That image is not found!",
                        returnUrl: returnUrl)
                    , JsonRequestBehavior.AllowGet);

            var filePath = Path.Combine(Server.MapPath("~/"), image.Url);
            _unitOfWork.Images.Remove(image);

            if (System.IO.File.Exists(filePath))
                System.IO.File.Delete(filePath);

            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(
                MessageAlertType.Success,
                message: "That image has been removed!",
                returnUrl: returnUrl));
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var image = await _unitOfWork.Images.Get(id.Value);

            if (image == null) return HttpNotFound();

            var dishes = await _unitOfWork.Dishes.GetDishesWithSimpleDetail();

            ViewBag.DishId = new SelectList(dishes, "Id", "Name", image.DishId);

            return View(image);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Edit([Bind(Include = "Id, Name, IsDisplay, DishId")] Image model)
        {
            var returnUrl = "/Images";

            if (!ModelState.IsValid)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                    message: @"Please enter all fields are required!"), JsonRequestBehavior.AllowGet);

            var image = await _unitOfWork.Images.Get(model.Id);

            var dish = await _unitOfWork.Dishes.Get(model.DishId);

            if (dish == null || image == null)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.BadRequest,
                    returnUrl), JsonRequestBehavior.AllowGet);

            var imageUpload = Request.Files["FileEdit"];

            if (imageUpload != null)
            {
                var validateFile = Utilities.HttpPostedFileBaseFilter(imageUpload);
                if (validateFile >= 0)
                {
                    var error = Utilities.HttpPostedFileBaseErrorMessage(validateFile);
                    return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                        message: error), JsonRequestBehavior.AllowGet);
                }

                var originalDirectory = new DirectoryInfo(Server.MapPath("~/Content/Dishes"));
                var directoryPath = Path.Combine(originalDirectory.ToString(), dish.Name);
                if (!Directory.Exists(directoryPath))
                    Directory.CreateDirectory(directoryPath);
                try
                {
                    var fileName = Guid.NewGuid() + ".jpg";
                    imageUpload.SaveAs(Path.Combine(directoryPath, fileName));
                    var oldFilePath = Path.Combine(Server.MapPath("~/"), image.Url);
                    if (System.IO.File.Exists(oldFilePath))
                        Task.Run(() => { System.IO.File.Delete(oldFilePath); }).Wait();
                    image.Url = $"Content/Dishes/{dish.Name}/{fileName}";
                }
                catch (Exception)
                {
                    return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.ServerError,
                        $"/Restaurants/Edit/{image.Id}"), JsonRequestBehavior.AllowGet);
                }
            }

            image.Name = model.Name;
            image.DishId = model.DishId;
            image.IsDisplay = model.IsDisplay;
            _unitOfWork.Images.Update(image);
            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Success,
                    message: @"This image has been updated successfully", returnUrl: returnUrl),
                JsonRequestBehavior.AllowGet);
        }
    }
}

FBru.WebAdmin/Controllers/KeywordsController.cs
using FBru.Repository.Entities;
using FBru.Repository.Interfaces;
using FBru.WebAdmin.Helpers;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FBru.WebAdmin.Controllers
{
    [AuthorizeFilter]
    public class KeywordsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public KeywordsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<ActionResult> Index()
        {
            var keywords = await _unitOfWork.Keywords.GetKeywordsWithoutDishes();

            return View(keywords);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name")] Keyword model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (await _unitOfWork.Keywords.SingleOrDefault(k => k.Name.ToLower() == model.Name.ToLower()) != null)
            {
                ModelState.AddModelError(string.Empty, @"This keyword is already exist!");
                return View(model);
            }


            _unitOfWork.Keywords.Add(model);
            await _unitOfWork.Completed();

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var keyword = await _unitOfWork.Keywords.Get(id.Value);

            if (keyword == null)
                return HttpNotFound();

            return View(keyword);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Edit([Bind(Include = "Id, Name")] Keyword model)
        {
            var returnUrl = "/Keywords";

            if (!ModelState.IsValid)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                    message: "Please enter all fields are required!"));

            var keyword = await _unitOfWork.Keywords.Get(model.Id);

            if (keyword == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl)
                    , JsonRequestBehavior.AllowGet);

            keyword.Name = model.Name;
            _unitOfWork.Keywords.Update(keyword);

            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(
                    MessageAlertType.Success,
                    message: "This keyword has been updated successfully!",
                    returnUrl: returnUrl)
                , JsonRequestBehavior.AllowGet);
        }


        public async Task<ActionResult> Detail(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var keyword = await _unitOfWork.Keywords.GetKeywordWithDishes(id.Value);

            if (keyword == null)
                return HttpNotFound();

            return View(keyword);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> DeleteDish(int? keywordId, int? dishId)
        {
            var returnUrl = "/Keywords";

            if (keywordId == null || dishId == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl),
                    JsonRequestBehavior.AllowGet);

            var keyword = await _unitOfWork.Keywords.Get(keywordId.Value);

            var dish = await _unitOfWork.Dishes.GetDishWithKeywords(dishId.Value);

            if (keyword == null && dish == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl),
                    JsonRequestBehavior.AllowGet);

            dish.Keywords.Remove(keyword);

            _unitOfWork.Dishes.Update(dish);
            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(
                    MessageAlertType.Success,
                    message: "That dish has been removed from this keyword successfully!")
                , JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int? id)
        {
            var returnUrl = "/Keywords";

            if (id == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl),
                    JsonRequestBehavior.AllowGet);

            var keyword = await _unitOfWork.Keywords.Get(id.Value);

            if (keyword == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl),
                    JsonRequestBehavior.AllowGet);

            _unitOfWork.Keywords.Remove(keyword);
            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(
                    MessageAlertType.Success,
                    message: "This keyword has been removed successfully!",
                    returnUrl: returnUrl)
                , JsonRequestBehavior.AllowGet);
        }
    }
}

FBru.WebAdmin/Views/Dishes/Detail.cshtml
@model FBru.DTO.DishDto

@{
    ViewBag.Title = "Detail";
    ViewBag.SubTitle = $"Dish: {Model.Name} - Id: {Model.Id}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles {
    @Styles.Render("~/content/datatables")
}
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            @Html.ActionLink("Edit", "Edit", new {id = Model.Id}, new {@class = "btn btn-warning btn-sm"})
            <a href="#" class="btn btn-danger btn-sm btn-delete-dish" data-dish-id="@Model.Id">Delete</a>
        </div>
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id, new {data_dish_id = Model.Id})
        <h3>Dish detail</h3>
        <table id="dishDetailTable" class="table table-bordered table-striped table-responsive">
            <thead>
            <tr>
                <th>Name</th>
                <th>Detail</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Id</td>
                <td>@Model.Id</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>@Model.Name</td>
            </tr>
            <tr>
                <td>Price</td>
                <td>@Model.Price</td>
            </tr>
            <tr>
                <td>Category</td>
                <td>@Html.ActionLink(Model.Category.Name, "Detail", "Categories", new {id = Model.Category.Id}, new {@class = "btn-link"})</td>
            </tr>
            <tr>
                <td>Restaurant</td>
                <td>@Html.ActionLink(Model.Restaurant.Name, "Detail", "Restaurants", new {id = Model.Restaurant.Id}, new {@class = "btn-link"})</td>
            </tr>
            </tbody>
        </table>
        <div class="form-group">
            <h3 class="margin-top-30">Keywords</h3>
            @Html.ActionLink("Create Keyword", "Create", "Keywords", null, new {@class = "btn btn-success btn-sm"})
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <ul class="list-group list-inline" id="keywordsTable">
                    @foreach (var item in Model.Keywords)
                    {
                        <li class="list-group-item">
                            <a href="@Url.Action("Detail", "Keywords", new {id = item.Id})">
                                <span class="text-info">@item.Name</span>
                            </a>
                            <a href="#" data-keyword-id="@item.Id" class="btn-delete-keyword">
                                <i class="fa fa-remove text-danger"></i>
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
        @if (Model.Description != null)
        {
            <div class="form-group">
                <h3 class="margin-top-30">Description</h3>

                <div class="panel panel-default">
                    <div class="panel-body panel-fixed">
                        @Html.Raw(HttpUtility.HtmlDecode(Model.Description))
                    </div>
                </div>
            </div>
        }
        <div class="form-group">
            <h3 class="margin-top-30">Images</h3>
            @Html.ActionLink("Create Image", "Create", "Images", new {id = Model.Id}, new {@class = "btn btn-success btn-sm"})
        </div>
        <table id="imagesTable" class="table table-striped table-bordered" width="100%">
            <thead>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Image</td>
                <td>Display</td>
                <td>Action</td>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Images)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>
                        <a href="#" class="btn-view-image" data-image-url="/@item.Url" data-image-title="@item.Name" data-toggle="modal" data-target="#imageModel">
                            <img src="~/@item.Url" class="img-responsive" alt="@item.Name" style="max-width: 200px"/>
                        </a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.IsDisplay)</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Images", new {id = item.Id}, new {@class = "btn btn-sm btn-warning"})
                        <button class="btn btn-sm btn-danger btn-delete-image" data-image-id="@item.Id">Delete</button>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <hr/>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

<div id="imageModel" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <img class="img-responsive img-thumbnail"/>
            </div>
        </div>

    </div>
</div>


@section scripts {
    @Scripts.Render("~/bundles/datatables")
    <script>
        $(document).ready(function() {
            var table = $("#imagesTable").DataTable({
                responsive: true,
                bSort: true
            });

            var addAntiForgeryToken = function(data) {
                data.__RequestVerificationToken = $("[name='__RequestVerificationToken']").val();
                return data;
            };

            $(".btn-delete-dish").on("click",
                function() {
                    var button = $(this);
                    bootbox.confirm("Are you sure you want to delete this dish?",
                        function(result) {
                            if (result) {
                                $.ajax({
                                    url: "/Dishes/Delete",
                                    data: addAntiForgeryToken({ id: button.attr("data-dish-id") }),
                                    method: "POST"
                                }).done(function(data) {
                                    if (data.Status === true) {
                                        toastr.success(data.Message);
                                        setTimeout(function() {
                                                window.location.href = window.location.origin + data.ReturnUrl;
                                            },
                                            1000);
                                    }
                                    if (data.Status === false && data.BadRequest === true) {
                                        toastr.error(data.Message);
                                        setTimeout(function() {
                                                window.location.href = window.location.origin + data.ReturnUrl;
                                            },
                                            1000);
                                    }
                                    if (data.Status === false && data.BadRequest === false) {
                                        toastr.error(data.Message);
                                        if (data.ReturnUrl != null) {
                                            setTimeout(function() {
                                                    window.location.href = window.location.origin + data.ReturnUrl;
                                                },
                                                1000);
                                        }
                                    }
                                }).fail(function() {
                                    toastr.error("Something unexpected happend!");
                                });
                            }
                        });
                });

            $("#imagesTable .btn-delete-image").on("click",
                function() {
                    var button = $(this);
                    bootbox.confirm("Are you sure you want to delete this image?",
                        function(result) {
                            if (result) {
                                $.ajax({
                                    url: "/Images/Delete",
                                    data: addAntiForgeryToken({ id: button.attr("data-image-id") }),
                                    method: "POST"
                                }).done(function(data) {
                                    if (data.Status === true) {
                                        table.row(button.parents("tr")).remove().draw();
                                        toastr.success(data.Message);
                                    }
                                    if (data.Status === false && data.BadRequest === true) {
                                        toastr.error(data.Message);
                                        setTimeout(function() {
                                                window.location.href = window.location.origin + data.ReturnUrl;
                                            },
                                            1000);
                                    }
                                }).fail(function() {
                                    toastr.error("Something unexpected happend!");
                                });
                            }
                        });
                });

            $("#keywordsTable .btn-delete-keyword").on("click",
                function() {
                    var button = $(this);
                    bootbox.confirm("Are you sure you want to delete this keyword over this dish?",
                        function(result) {
                            if (result) {
                                $.ajax({
                                    url: "/Keywords/DeleteDish",
                                    data: addAntiForgeryToken({
                                        keywordId: button.attr("data-keyword-id"),
                                        dishId: $("#Id").attr("data-dish-id")
                                    }),
                                    method: "POST"
                                }).done(function(data) {
                                    if (data.Status === true) {
                                        toastr.success("That keyword has been removed!");
                                        button.parents("li").remove().draw();
                                    }
                                    if (data.Status === false && data.BadRequest === true) {
                                        toastr.error(data.Message);
                                        setTimeout(function() {
                                                window.location.href = window.location.origin + data.ReturnUrl;
                                            },
                                            1000);
                                    }
                                }).fail(function() {
                                    toastr.error("Something unexpected happend!");
                                });
                            }
                        });
                });

            $("#imagesTable .btn-view-image").on("click",
                function() {
                    var button = $(this);
                    var modalImage = $("#imageModel .img-responsive");
                    var modalTitle = $("#imageModel .modal-title");
                    var imageUrl = button.attr("data-image-url");
                    var title = button.attr("data-image-title");
                    modalImage.attr("src", imageUrl);
                    modalTitle.text(title);
                });
        });
    </script>
}