FBru.WebAdmin/Controllers/Api/KeywordsController.cs
using FBru.Repository.Interfaces;
using FBru.WebAdmin.Helpers;
using Microsoft.Ajax.Utilities;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;

namespace FBru.WebAdmin.Controllers.Api
{
    [RoutePrefix("api")]
    public class KeywordsController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;

        public KeywordsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        [Route("keywords/{query?}")]
        public async Task<IHttpActionResult> GetKeywords(string query = null)
        {
            var keywords = await _unitOfWork.Keywords.GetKeywordsWithoutDishes();

            if (!string.IsNullOrWhiteSpace(query))
                keywords = keywords
                    .Where(k => k.Name.Contains(query))
                    .OrderBy(k => k.Id);

            return Ok(keywords);
        }

        [HttpGet]
        [Route("keyword/search/{query}")]
        public async Task<IHttpActionResult> SearchKeyword(string query)
        {
            if (query == null)
            {
                return NotFound();
            }
            var keyword = await _unitOfWork.Keywords.GetKeywordWithDishes(query);
            keyword.Dishes.ForEach(d => d.ImageUrl = Constrains.ServerUrl + d.ImageUrl);
            return Ok(keyword);
        }
    }
}

FBru.WebAdmin/Controllers/Api/RestaurantsController.cs
using FBru.Repository.Interfaces;
using FBru.WebAdmin.Helpers;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace FBru.WebAdmin.Controllers.Api
{
    [RoutePrefix("api")]
    public class RestaurantsController : ApiController
    {
        private const int MaxPageSize = 10;

        private readonly IUnitOfWork _unitOfWork;

        public RestaurantsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Route("restaurants/{id}", Name = "RestaurantForId")]
        public async Task<IHttpActionResult> Get(int? id)
        {
            if (id == null)
                return BadRequest();

            var restaurant = await _unitOfWork.Restaurants.GetRestaurantWithDishesHaveCategoryDto(id.Value);

            if (restaurant == null)
                return NotFound();

            restaurant.ImageUrl = Constrains.ServerUrl + restaurant.ImageUrl;

            restaurant.Dishes.ForEach(d => d.ImageUrl = Constrains.ServerUrl + d.ImageUrl);

            return Ok(restaurant);
        }

        [Route("restaurants/v1/page/{page}/{pageSize}", Name = "RestaurantsList")]
        public async Task<IHttpActionResult> Get(int page = 1, int pageSize = MaxPageSize)
        {
            var restaurants = await _unitOfWork.Restaurants.GetRestaurantsWithNumberOfDishes();

            var restaurantsArray = restaurants.ToArray();

            var totalCount = restaurantsArray.Count();
            var totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

            var paginationHeader = new
            {
                currentPage = page,
                pageSize,
                totalCount,
                totalPages
            };

            HttpContext.Current.Response.Headers.Add("X-Pagination",
                JsonConvert.SerializeObject(paginationHeader));

            var skip = pageSize * (page - 1);
            var takeLimited = totalCount - skip;
            var take = pageSize;
            if (pageSize > takeLimited)
                take = takeLimited;

            var restaurantsDto = restaurantsArray.Skip(skip).Take(take).ToList();
            restaurantsDto.ForEach(r => r.ImageUrl = Constrains.ServerUrl + r.ImageUrl);

            return Ok(restaurantsArray.Skip(skip).Take(take).ToList());
        }
    }
}

FBru.WebAdmin/Controllers/CategoriesController.cs
using System.IO;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using FBru.Repository.Entities;
using FBru.Repository.Interfaces;
using FBru.WebAdmin.Helpers;

namespace FBru.WebAdmin.Controllers
{
    [AuthorizeFilter]
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<ActionResult> Index()
        {
            var categories = await _unitOfWork.Categories.GetCategoriesWithoutDishes();

            return View(categories);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Create([Bind(Include = "Name, Icon")] Category model)
        {
            if (!ModelState.IsValid)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                    message: "Please enter all fields are required!"));

            if (await _unitOfWork.Categories.SingleOrDefault(c => c.Name.ToLower() == model.Name.ToLower()) != null)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                    message: "This category name is already exist, try again!"));

            _unitOfWork.Categories.Add(model);

            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(
                MessageAlertType.Success,
                message: "This category name has been added successfully!",
                returnUrl: $"/Categories/Detail/{model.Id}"));
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var category = await _unitOfWork.Categories.Get(id.Value);

            if (category == null)
                return HttpNotFound();

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Edit([Bind(Include = "Id, Name, Icon")] Category model)
        {
            var returnUrl = "/Categories";

            if (!ModelState.IsValid)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                    message: "Please enter all fields are required!"));

            var category = await _unitOfWork.Categories.Get(model.Id);

            if (category == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl)
                    , JsonRequestBehavior.AllowGet);

            category.Name = model.Name;
            category.Icon = model.Icon;

            _unitOfWork.Categories.Update(category);
            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(
                    MessageAlertType.Success,
                    message: "This category has been updated successfully!",
                    returnUrl: $"/Categories/Detail/{category.Id}")
                , JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int? id)
        {
            var returnUrl = "/Categories";
            if (id == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl),
                    JsonRequestBehavior.AllowGet);
            var category = await _unitOfWork.Categories.GetCategoryWithDishes(id.Value);

            if (category == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl)
                    , JsonRequestBehavior.AllowGet);

            foreach (var dish in category.Dishes)
            foreach (var image in dish.Images)
            {
                var filePath = Path.Combine(Server.MapPath("~/"), image.Url);
                if (System.IO.File.Exists(filePath))
                    Task.Run(() => { System.IO.File.Delete(filePath); }).Wait();
            }

            _unitOfWork.Categories.Remove(category);
            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(
                    MessageAlertType.Success,
                    message: "That category has been deleted successfully!",
                    returnUrl: returnUrl)
                , JsonRequestBehavior.AllowGet);
        }


        public async Task<ActionResult> Detail(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var category = await _unitOfWork.Categories.GetCategoryWithDishesHaveRestaurants(id.Value);

            if (category == null)
                return HttpNotFound();

            return View(category);
        }
    }
}

FBru.WebAdmin/Controllers/DishesController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using FBru.DTO;
using FBru.Repository.Entities;
using FBru.Repository.Interfaces;
using FBru.WebAdmin.Helpers;
using FBru.WebAdmin.Models;

namespace FBru.WebAdmin.Controllers
{
    [AuthorizeFilter]
    public class DishesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DishesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Dishes
        public async Task<ActionResult> Index()
        {
            var dishes = await _unitOfWork.Dishes.GetDishesWithRestaurantAndCategory();

            return View(dishes);
        }

        public async Task<ActionResult> Create()
        {
            var categories = await _unitOfWork.Categories.GetCategoriesWithDishes();
            ViewBag.CategoryId = new SelectList(categories, "Id", "Name");
            var restaurants = await _unitOfWork.Restaurants.GetRestaurantsWithoutDishes();
            ViewBag.RestaurantId = new SelectList(restaurants, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Create(
            [Bind(Include = "Name, Description, Price, CategoryId, RestaurantId, KeywordIds")] DishModel model)
        {
            var returnUrl = "/Dishes/Create";

            if (!ModelState.IsValid)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                    message: "Please enter all fields are required!"));

            var categoryId = await _unitOfWork.Categories.SingleOrDefault(c => c.Id == model.CategoryId);

            var restaurantId = await _unitOfWork.Restaurants.SingleOrDefault(r => r.Id == model.RestaurantId);

            if (categoryId == null || restaurantId == null)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.BadRequest,
                    returnUrl));

            var dish = Mapper.Map<DishModel, Dish>(model);

            if (model.KeywordIds.Any())
                foreach (var kw in model.KeywordIds)
                {
                    var findKeyword = await _unitOfWork.Keywords.SingleOrDefault(k => kw == k.Id);
                    dish.Keywords.Add(findKeyword);
                }

            _unitOfWork.Dishes.Add(dish);
            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Success,
                message: "This dish has been added successfully! You will be moved to next page to add some images.",
                returnUrl: $"/Images/Create/{dish.Id}"));
        }

        public async Task<JsonResult> GetKeywords(string query = null)
        {
            var keywords = await _unitOfWork.Keywords.GetKeywordsWithoutDishes();

            if (!string.IsNullOrWhiteSpace(query))
                keywords = keywords
                    .Where(k => k.Name.Contains(query))
                    .OrderBy(k => k.Id);

            return Json(keywords, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Detail(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var dish = await _unitOfWork.Dishes.GetDishWithFullDetails(id.Value);

            if (dish == null)
                return HttpNotFound();

            return View(dish);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int? id)
        {
            var returnUrl = "/Dishes";
            if (id == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl),
                    JsonRequestBehavior.AllowGet);
            var dish = await _unitOfWork.Dishes.GetDishWithImagesAndKeywords(id.Value);

            if (dish == null)
                return Json(MessageAlertCenter.GetMessageAlert(
                        MessageAlertType.BadRequest,
                        returnUrl)
                    , JsonRequestBehavior.AllowGet);

            foreach (var item in dish.Images)
            {
                var filePath = Path.Combine(Server.MapPath("~/"), item.Url);
                if (System.IO.File.Exists(filePath))
                    Task.Run(() => { System.IO.File.Delete(filePath); }).Wait();
            }

            _unitOfWork.Dishes.Remove(dish);
            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(
                MessageAlertType.Success,
                message: "That dish has been removed successfully!",
                returnUrl: returnUrl));
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var dish = await _unitOfWork.Dishes.GetDishWithFullDetails(id.Value);

            if (dish == null)
                return HttpNotFound();

            var dishDto = Mapper.Map<DishDto, DishModel>(dish);

            var categories = await _unitOfWork.Categories.GetCategoriesWithDishes();
            ViewBag.CategoryId = new SelectList(categories, "Id", "Name", dish.Category.Id);

            var restaurants = await _unitOfWork.Restaurants.GetRestaurantsWithoutDishes();
            ViewBag.RestaurantId = new SelectList(restaurants, "Id", "Name", dish.Restaurant.Id);

            var keywordsId = "";

            foreach (var keyword in dishDto.Keywords)
                keywordsId += $"{keyword.Id} ";

            ViewBag.KeywordIds = keywordsId.Trim();

            return View(dishDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Edit(
            [Bind(Include = "Id, Name, Description, Price, CategoryId, RestaurantId, KeywordIds")] DishModel model)
        {
            var returnUrl = "/Dishes";
            if (!ModelState.IsValid)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Invalid,
                    message: "Please enter all fields are required!"));

            var categoryId = await _unitOfWork.Categories.SingleOrDefault(c => c.Id == model.CategoryId);

            var restaurantId = await _unitOfWork.Restaurants.SingleOrDefault(r => r.Id == model.RestaurantId);

            var dish = await _unitOfWork.Dishes.Get(model.Id);

            if (categoryId == null || restaurantId == null || dish == null)
                return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.BadRequest,
                    returnUrl));

            dish.Keywords = new List<Keyword>();

            if (model.KeywordIds.Any())
                foreach (var kw in model.KeywordIds)
                {
                    var findKeyword = await _unitOfWork.Keywords.SingleOrDefault(k => kw == k.Id);
                    dish.Keywords.Add(findKeyword);
                }
            dish.CategoryId = model.CategoryId;
            dish.RestaurantId = model.RestaurantId;
            dish.Name = model.Name;
            dish.Price = model.Price;
            dish.Description = model.Description;

            _unitOfWork.Dishes.Update(dish);
            await _unitOfWork.Completed();

            return Json(MessageAlertCenter.GetMessageAlert(MessageAlertType.Success,
                message: "This dish has been updated successfully!",
                returnUrl: $"/Dishes/Detail/{dish.Id}"));
        }
    }
}

FBru.WebAdmin/Views/Keywords/Create.cshtml
@model FBru.Repository.Entities.Keyword
@{
    ViewBag.Title = "Create";
    ViewBag.SubTitle = "Enter a name to add new keyword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success btn-sm"/>
                    </div>
                </div>
            </div>
        }

        <hr/>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

FBru.WebAdmin/Views/Keywords/Detail.cshtml
@model FBru.DTO.KeywordWithDishesDto
@{
    ViewBag.Title = "Detail";
    ViewBag.SubTitle = $"Keyword: {Model.Name} - Id: {Model.Id}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles {
    @Styles.Render("~/content/datatables")
}
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            @Html.ActionLink("Edit", "Edit", new {id = Model.Id}, new {@class = "btn btn-warning btn-sm"})
            <a href="#" class="btn btn-danger btn-sm btn-delete-keyword" data-keyword-id="@Model.Id">Delete</a>
        </div>
        @Html.AntiForgeryToken()
        <h3>Keyword detail</h3>
        <table id="keyworddishDetailTable" class="table table-bordered table-striped table-responsive">
            <thead>
            <tr>
                <th>Name</th>
                <th>Detail</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Id</td>
                <td>@Model.Id</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>@Model.Name</td>
            </tr>
            </tbody>
        </table>
        <div class="form-group">
            <h3 class="margin-top-30">Dishes</h3>
            @Html.ActionLink("Create Dish", "Create", "Dishes", null, new {@class = "btn btn-success btn-sm"})
        </div>
        <table id="dishesTable" class="table table-striped table-bordered table-hover" width="100%">
            <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Image</td>
                <td>Category</td>
                <td>Restaurant</td>
                <td>Price</td>
                <td>Action</td>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Dishes)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@Html.Raw(item.ImageUrl != null ? $"<a href='#' class='btn-view-image' data-image-url='/{item.ImageUrl}' data-image-title='{item.Name}' data-toggle='modal' data-target='#imageModel'><img src='/{item.ImageUrl}' class='img-responsive' style='width: 100px;'/></a>" : "No")</td>
                    <td>@Html.ActionLink(item.Category.Name, "Detail", "Categories", new {id = item.Category.Id}, new {@class = "btn-link"})</td>
                    <td>@Html.ActionLink(item.Restaurant.Name, "Detail", "Restaurants", new {id = item.Restaurant.Id}, new {@class = "btn-link"})</td>
                    <td>@item.Price</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Dishes", new {id = item.Id}, new {@class = "btn btn-sm btn-warning"})
                        @Html.ActionLink("Detail", "Detail", "Dishes", new {id = item.Id}, new {@class = "btn btn-sm btn-info"})
                        <button class="btn btn-sm btn-danger btn-delete" data-keyword-id="@Model.Id" data-dish-id="@item.Id">Delete</button>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <hr/>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

<div id="imageModel" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <img class="img-responsive img-thumbnail"/>
            </div>
        </div>

    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/datatables")
    <script>
        $(document).ready(function() {
            var table = $("#dishesTable").DataTable({
                responsive: true,
                bSort: true
            });

            var addAntiForgeryToken = function(data) {
                data.__RequestVerificationToken = $("[name='__RequestVerificationToken']").val();
                return data;
            };

            $(".btn-delete-keyword").on("click",
                function() {
                    var button = $(this);
                    bootbox.confirm("Are you sure you want to delete this keyword from these dishes?",
                        function(result) {
                            if (result) {
                                $.ajax({
                                    url: "/Keywords/Delete",
                                    data: addAntiForgeryToken({ id: button.attr("data-keyword-id") }),
                                    method: "POST"
                                }).done(function(data) {
                                    if (data.Status === true) {
                                        toastr.success(data.Message);
                                        setTimeout(function() {
                                                window.location.href = window.location.origin + data.ReturnUrl;
                                            },
                                            1000);
                                    }
                                    if (data.Status === false && data.BadRequest === true) {
                                        toastr.error(data.Message);
                                        setTimeout(function() {
                                                window.location.href = window.location.origin + data.ReturnUrl;
                                            },
                                            1000);
                                    }
                                    if (data.Status === false && data.BadRequest === false) {
                                        toastr.error(data.Message);
                                        if (data.ReturnUrl != null) {
                                            setTimeout(function() {
                                                    window.location.href = window.location.origin + data.ReturnUrl;
                                                },
                                                1000);
                                        }
                                    }
                                }).fail(function() {
                                    toastr.error("Something unexpected happend!");
                                });
                            }
                        });
                });

            $("#dishesTable .btn-delete").on("click",
                function() {
                    var button = $(this);
                    bootbox.confirm("Are you sure you want to delete this dish from this keyword?",
                        function(result) {
                            if (result) {

                                $.ajax({
                                    url: "/Keywords/DeleteDish",
                                    data: addAntiForgeryToken({
                                        keywordId: button.attr("data-keyword-id"),
                                        dishId: button.attr("data-dish-id")
                                    }),
                                    method: "POST"
                                }).done(function(data) {
                                    if (data.Status === true) {
                                        toastr.success(data.Message);
                                        table.row(button.parents("tr")).remove().draw();
                                    }
                                    if (data.Status === false && data.BadRequest === true) {
                                        toastr.error(data.Message);
                                        setTimeout(function() {
                                                window.location.href = window.location.origin + data.ReturnUrl;
                                            },
                                            1000);
                                    }
                                }).fail(function() {
                                    toastr.error("Something unexpected happend!");
                                });
                            }
                        });
                });

            $("#dishesTable .btn-view-image").on("click",
                function() {
                    var button = $(this);
                    var modalImage = $("#imageModel .img-responsive");
                    var modalTitle = $("#imageModel .modal-title");
                    var imageUrl = button.attr("data-image-url");
                    var title = button.attr("data-image-title");
                    modalImage.attr("src", imageUrl);
                    modalTitle.text(title);
                });
        });
    </script>
}

FBru.WebAdmin/Views/Keywords/Edit.cshtml
@model FBru.Repository.Entities.Keyword

@{
    ViewBag.Title = "Edit";
    ViewBag.SubTitle = "Enter new keyword name to update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <form id="editKeyword">
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button class="btn btn-success btn-sm">Save</button>
                    </div>
                </div>
            </div>
        </form>
        <hr/>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function() {
            $("#editKeyword").validate();

            $("#editKeyword").submit(function(e) {
                e.preventDefault();
                var vm = {
                    __RequestVerificationToken: $("[name='__RequestVerificationToken']").val(),
                    Name: $("#Name").val().trim(),
                    Id: $("#Id").val()
                };


                $.ajax({
                    url: "/Keywords/Edit",
                    method: "post",
                    data: vm
                }).done(function(data) {
                    if (data.Status === true) {
                        toastr.success(data.Message);
                        setTimeout(function() {
                                window.location.href = window.location.origin + data.ReturnUrl;
                            },
                            1000);
                    }
                    if (data.Status === false && data.BadRequest === true) {
                        toastr.error(data.Message);
                        setTimeout(function() {
                                window.location.href = window.location.origin + data.ReturnUrl;
                            },
                            1000);
                    }
                    if (data.Status === false && data.BadRequest === false) {
                        toastr.error(data.Message);
                        if (data.ReturnUrl != null) {
                            setTimeout(function() {
                                    window.location.href = window.location.origin + data.ReturnUrl;
                                },
                                1000);
                        }
                    }
                }).fail(function() {
                    toastr.error("Something unexpected happend!");
                });
            });
        });
    </script>
}